### ISSUE TITLE
Dependency on `bigfloat` package

### ISSUE THREAD

**Issue by chazeon** [MineralsCloud/qha#47]
The package `bigfloat` is the high precision arithmetic used by the Helmholtz free energy part of the calculator to do exponential and logarithm calculation. It is not actively maintained and supports Python 3.5 and 3.6 to date. This outdated package could limit the possibility for our code to be port to Python 3.7 or later versions. As Python 3.7 has its official release, as is mentioned in #46, this could be an issue. So I'm thinking of finding alternatives.

Another package [`gmpy`](https://github.com/aleaxit/gmpy) is more actively developed and maintained, and is marked as a [superseder](https://www.lfd.uci.edu/~gohlke/pythonlibs/#bigfloat) in the [Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/) page, could be the option.

Yet do we actually need the precision, as is indicated in the code, `500` for our calculator? Just for `log` and `exp`? Maybe `numpy`'s `float64` is just good enough for the job. Even our unit conversion code could not maintain such high a precision as that.

We should test the outcome of using more convenient ways; and we could maybe give options for drivers and list them as “[extra](https://setuptools.readthedocs.io/en/latest/setuptools.html#id15)” dependencies for the package, like the [Beautiful Soup 4](https://www.crummy.com/software/BeautifulSoup/bs4/doc/index.html#installing-a-parser) package does?

**Comment by singularitti** [comment]
Merged.
